openapi: 3.0.1
info:
  title: p4pa-auth
  description: Api and Models
  version: 0.0.1
servers:
  - url: https://api.dev.p4pa.pagopa.it/payhub
paths:
  /auth:
    get:
      tags:
        - authToken
      operationId: authToken
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorDTO'
components:
  schemas:
    AuthErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - AUTH_TOKEN_EXPIRED_DATE
            - AUTH_GENERIC_ERROR
            - AUTH_INVALID_TOKEN
            - AUTH_INVALID_REQUEST
          description: >-
            "ENG: Error code: AUTH_TOKEN_EXPIRED_DATE: Token date expired,
             AUTH_INVALID_TOKEN: The token is not valid
             AUTH_INVALID_REQUEST: Something went wrong handling request,
             AUTH_GENERIC_ERROR: Application Error - IT: Codice di errore:
             AUTH_TOKEN_EXPIRED_DATE: Token scaduto,
             AUTH_INVALID_TOKEN: Il Token non è valido
             AUTH_INVALID_REQUEST: Qualcosa è andato storto durante l'invio della richiesta,
             AUTH_GENERIC_ERROR: Errore generico"
        message:
          type: string
          description: "ENG: Error message - IT: Messaggio di errore"
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
