spring:
    application:
        name: ${artifactId}
        version: ${version}
    jmx.enabled: true


jwt:
    audience: "\${JWT_TOKEN_AUDIENCE:application-audience}"
    access-token:
        expire-in: "\${JWT_TOKEN_EXPIRATION_SECONDS:3600}"
        private-key: "\${JWT_TOKEN_PRIVATE_KEY:}"
        public-key: "\${JWT_TOKEN_PUBLIC_KEY:}"
    external-token:
        base-url: "\${JWT_EXTERNAL_TOKEN_BASE_URL:https://auth.server.com}"
        issuer: "\${JWT_EXTERNAL_TOKEN_ISS:externalauthentication-server-issuer}"


management:
    endpoint:
        health:
            probes.enabled: true
            group:
                readiness.include: "*"
                liveness.include: livenessState,diskSpace,ping
    endpoints:
        jmx:
            exposure.include: "*"
        web:
            exposure.include: info, health