spring:
    application:
        name: ${artifactId}
        version: ${version}
    jmx.enabled: true


auth:
    token:
        issuer: "\${AUTH_TOKEN_ISS:https://dev.selfcare.pagopa.it}"
        audience: "\${AUTH_TOKEN_AUD:dev.piattaformaunitaria.pagopa.it}"
        jwk: "\${AUTH_TOKEN_JWK:https://dev.selfcare.pagopa.it}"


management:
    endpoint:
        health:
            probes.enabled: true
            group:
                readiness.include: "*"
                liveness.include: livenessState,diskSpace,ping
    endpoints:
        jmx:
            exposure.include: "*"
        web:
            exposure.include: info, health