microservice-chart:
  image:
    repository: p4pauitncorecommonacr.azurecr.io/p4paauth
    tag: latest
    pullPolicy: Always

    ingress:
      host: "hub.internal.uat.p4pa.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "4Gi"
      cpu: "300m"

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 1
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
  #          value: "70"

  envConfig:
    ENV: "UAT"
    JAVA_TOOL_OPTIONS: "-Xms128m -Xmx4g -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"


  keyvault:
    name: "p4pa-u-payhub-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
